[package]
name = "rori_desktop_endpoint"
version = "0.0.0"
authors = ["AmarOk <amarok@enconn.fr>"]

[dependencies]
rustc-serialize = "*"
regex = "*"
log = "*"
env_logger = "*"
openssl = "0.7"
rust-crypto = "^0.2"
